name: Publish binaries to GitHub
on:
  release:
    types: [created]
permissions: read-all

jobs:
  release:
    name: Create release binaries
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3
      - name: Generate binaries

      - name: Upload binaries
        uses: skx/github-action-publish-binaries@master
        with:
          args: 'build/openbin-*'
          