name: Publish binaries to GitHub
on:
  workflow_dispatch:
  release:
    types: [created]
permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read # To read workflow path.
    strategy:
      matrix:
        os:
          - linux
          - windows
          - darwin
        arch:
          - amd64
          - arm64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.8.0
    with:
      go-version: 1.19.4
      config-file: .slsa-goreleaser/${{ matrix.os }}-${{ matrix.arch }}.yml
      # =============================================================================================================
      #     Optional: For more options, see https://github.com/slsa-framework/slsa-github-generator#golang-projects
      # =============================================================================================================
